### PR TITLE
Input 'textStyle' field is not optional #68

### LINKED ISSUE #67: Input `bg` field is not optional
It throws an error: "ut: bg is not defined, please define it."

### LINKED ISSUE #68: Input 'textStyle' field is not optional
Screenshot 2023-05-05 at 17 58 13

### PR DESCRIPTION
**Pull request by CyberDex**
fixes #68
fixes #67

### CODE REVIEW

File: src/Input.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { getView } from './utils/helpers/view';
 import { Padding } from './utils/HelpTypes';
 
 export type InputOptions = {
-    bg?: Container | string;
+    bg: Container | string;
```
Comment (CyberDex) [inline src/Input.ts:11]: Fix for Input bg field is not optional #67

File: src/Input.ts [hunk 2]
```diff
@@ -154,6 +154,8 @@ export class Input extends Container
             align: 'center'
         } as TextStyle;
 
+        this.options.textStyle = options.textStyle ?? defaultTextStyle;
+
```
Comment (CyberDex) [inline src/Input.ts:158]: Fix for Input 'textStyle' field is not optional #68

**Review by Zyie — APPROVED** [review]
